### ISSUE TITLE
Update Webpack to 5.76.0

### ISSUE THREAD

**Issue by silvanaweb** [vite-plugin/vite-plugin-esmodule#11]
Hello, I am solving critical risks in my company app and one of the critical risks comes from this plugin because it has a Webpack version of 5.74.0.
According to the report provided by MEND, this is the reason it should be upgraded to 5.76.0:

> Webpack 5 before 5.76.0 does not avoid cross-realm object access. ImportParserPlugin.js mishandles the magic comment feature. An attacker who controls a property of an untrusted object can obtain access to the real global object.

Would you mind helping with this?

**Comment by caoxiemeihao** [comment]
Haha! Perhaps `webpack` is more appropriate as `peerDependencies`.
I'd be happy to get you help :)

I just created a new branch `v1.5.0`

**Comment by silvanaweb** [comment]
Thank you. Have you created a pull request?

**Comment by caoxiemeihao** [comment]
I haven't done anything yet, just created a branch.
You can create a PR to the `v1.5.0` branch, and eventually it will be a PR to the main branch as a release branch.

**Comment by silvanaweb** [comment]
If I bump the version of webpack, how can I test that nothing is broken? How do you test it?

**Comment by caoxiemeihao** [comment]
I'll be working on a new version this weekend that will have some API chagnes :)

**Comment by silvanaweb** [comment]
Thank you very much 草鞋没号 🙏🏼
Please remember to bump WebPack to 5.76.0, many people will be grateful :)

**Comment by caoxiemeihao** [comment]
The new version will not force the Webpack version, but will leave it up to the user to specify which version to use :)
