### ISSUE TITLE
Getting a TypeScript error from index.d.ts

### ISSUE THREAD

**Issue by astoilkov** [vite-plugin/vite-plugin-esmodule#8]
`node_modules/vite-plugin-esmodule/index.d.ts:11:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.`:
<img width="692" alt="CleanShot 2022-09-12 at 14 14 10@2x" src="https://user-images.githubusercontent.com/884810/189639920-1d7b100d-7535-4154-a114-e9697aafd6ce.png">

**Comment by caoxiemeihao** [comment]
tsconfig.json

```diff
{
  "compilerOptions": {
+   "skipLibCheck": true
  }
}

```

**Comment by astoilkov** [comment]
Hi @caoxiemeihao.

I tried this solution and it works. However, enabling this will prevent me to see errors associated with library checks. Can the TypeScript types be fixed so the error doesn't appear? Thanks!

BTW, did Vite give a community role?

Sorry, I closed the issue accidentally.

**Comment by caoxiemeihao** [comment]
@astoilkov 👋

Yes, I will fix it.
The repositories in [vite-plugin](https://github.com/vite-plugin) should all be updated, I need more time to do these things.
The Vite community has give me an ecosystem maintenance role on Discord, thank you! 😄
I've been concentrating  on refactoring `vite-plugin-electron@0.10.0` recently. **It's coming soon**, and the `vite-plugin-electron-renderer` will be supported in Worker.

**Comment by astoilkov** [comment]
> Yes, I will fix it.

Awesome.

> The repositories in vite-plugin should all be updated, I need more time to do these things.

Yeah, makes sense. No worries. Thank you for working on this!

> The Vite community has give me an ecosystem maintenance role on Discord, thank you! 😄

Great news. I'm very happy for you. By the way, I tried to follow you on GitHub but there is no follow button.

> I've been concentrating on refactoring vite-plugin-electron@0.10.0 recently. It's coming soon, and the vite-plugin-electron-renderer will be supported in Worker.

That's amazing news! I've also started working on abstraction for Electron + Vite (I call it `ev`). The idea is to just call `ev dev` just like `vite dev` but for Electron apps. At some point, I can open-source and mention that it's mainly possible because of you:
![image](https://user-images.githubusercontent.com/884810/194714188-c7007635-6d43-469d-85cd-828f583a5646.png)

**Comment by caoxiemeihao** [comment]
Thank you for your promotion of [electron-vite](https://github.com/electron-vite), The same I hope you can join electron-vite, it will become better because of you. 😄

<img width="733" alt="image" src="https://user-images.githubusercontent.com/26263658/194732944-2d660ed1-940b-4f16-a20c-2b661f25a86b.png">

**Comment by astoilkov** [comment]
Wow. Thanks for the invitation. I joined. I don't understand much about how Vite works but I can help you with documentation and API design. I'm pretty good at both.

**Comment by astoilkov** [comment]
Is there any chat I can use to contact you (instead of these GitHub issues)?

**Comment by caoxiemeihao** [comment]
We can use Discord, I've made a friend requiest to you.
